# Generated by Django 4.1.3 on 2022-11-12 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('idkategorije', models.AutoField(primary_key=True, serialize=False)),
                ('categoryname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseid', models.AutoField(primary_key=True, serialize=False)),
                ('coursename', models.CharField(max_length=100)),
                ('kraticacourse', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oglas',
            fields=[
                ('oglasid', models.AutoField(primary_key=True, serialize=False)),
                ('oglastitle', models.CharField(max_length=100)),
                ('oglasdescription', models.CharField(max_length=100)),
                ('dateofcreation', models.DateField()),
                ('vrstaoglasa', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'oglas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Registrirani',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('useravatar', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('created', models.DateField()),
            ],
            options={
                'db_table': 'registrirani',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('replyid', models.AutoField(primary_key=True, serialize=False)),
                ('replytext', models.CharField(max_length=1000)),
                ('replycreated', models.DateField()),
                ('statusvalue', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'replies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudyProgramme',
            fields=[
                ('programmeid', models.AutoField(primary_key=True, serialize=False)),
                ('programename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'study_programme',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Deletedoglas',
            fields=[
                ('explanation', models.CharField(max_length=1000)),
                ('oglasid', models.OneToOneField(db_column='oglasid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.oglas')),
            ],
            options={
                'db_table': 'deletedoglas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('grade', models.IntegerField()),
                ('instructorid', models.OneToOneField(db_column='instructorid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.registrirani')),
            ],
            options={
                'db_table': 'grade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('userid', models.OneToOneField(db_column='userid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.registrirani')),
            ],
            options={
                'db_table': 'moderator',
                'managed': False,
            },
        ),
    ]
